# coding: utf-8

CHARS = {u"¡": None, u"¢": None, u"£": None, u"¤": None, u"¥": None, u"¦": None, u"§": None, u"¨": None, u"©": None,
         u"ª": None, u"«": None, u"¬": None,  u"®": None, u"¯": None, u"°": None, u"±": None, u"²": None, u"³": None,
         u"´": None, u"µ": None, u"¶": None, u"·": None, u"¸": None, u"¹": None, u"º": None, u"»": None, u"¼": None,
         u"½": None, u"¾": None, u"¿": None, u"À": None, u"Á": None, u"Â": None, u"Ã": None, u"Ä": None, u"Å": None,
         u"Æ": None, u"Ç": None, u"È": None, u"É": None, u"Ê": None, u"Ë": None, u"Ì": None, u"Í": None, u"Î": None,
         u"Ï": None, u"Ð": None, u"Ñ": None, u"Ò": None, u"Ó": None, u"Ô": None, u"Õ": None, u"Ö": None, u"×": None,
         u"Ø": None, u"Ù": None, u"Ú": None, u"Û": None, u"Ü": None, u"Ý": None, u"Þ": None, u"ß": None, u"à": None,
         u"á": None, u"â": None, u"ã": None, u"ä": None, u"å": None, u"æ": None, u"ç": None, u"è": None, u"é": None,
         u"ê": None, u"ë": None, u"ì": None, u"í": None, u"î": None, u"ï": None, u"ð": None, u"ñ": None, u"ò": None,
         u"ó": None, u"ô": None, u"õ": None, u"ö": None, u"÷": None, u"ø": None, u"ù": None, u"ú": None, u"û": None,
         u"ü": None, u"ý": None, u"þ": None, u"ÿ": None, u"Œ": None, u"œ": None, u"Š": None, u"š": None, u"Ÿ": None,
         u"ƒ": None, u"–": None, u"—": None, u"‘": None, u"’": None, u"‚": None, u"“": None, u"”": None, u"„": None,
         u"†": None, u"‡": None, u"•": None, u"…": None, u"‰": None, u"€": None, u"™": None}

NUMBS = {u"&#160;": None, u"&#161;": None, u"&#162;": None, u"&#163;": None, u"&#164;": None, u"&#165;": None,
         u"&#166;": None, u"&#167;": None, u"&#168;": None, u"&#169;": None, u"&#170;": None, u"&#171;": None,
         u"&#172;": None, u"&#173;": None, u"&#174;": None, u"&#175;": None, u"&#176;": None, u"&#177;": None,
         u"&#178;": None, u"&#179;": None, u"&#180;": None, u"&#181;": None, u"&#182;": None, u"&#183;": None,
         u"&#184;": None, u"&#185;": None, u"&#186;": None, u"&#187;": None, u"&#188;": None, u"&#189;": None,
         u"&#190;": None, u"&#191;": None, u"&#192;": None, u"&#193;": None, u"&#194;": None, u"&#195;": None,
         u"&#196;": None, u"&#197;": None, u"&#198;": None, u"&#199;": None, u"&#200;": None, u"&#201;": None,
         u"&#202;": None, u"&#203;": None, u"&#204;": None, u"&#205;": None, u"&#206;": None, u"&#207;": None,
         u"&#208;": None, u"&#209;": None, u"&#210;": None, u"&#211;": None, u"&#212;": None, u"&#213;": None,
         u"&#214;": None, u"&#215;": None, u"&#216;": None, u"&#217;": None, u"&#218;": None, u"&#219;": None,
         u"&#220;": None, u"&#221;": None, u"&#222;": None, u"&#223;": None, u"&#224;": None, u"&#225;": None,
         u"&#226;": None, u"&#227;": None, u"&#228;": None, u"&#229;": None, u"&#230;": None, u"&#231;": None,
         u"&#232;": None, u"&#233;": None, u"&#234;": None, u"&#235;": None, u"&#236;": None, u"&#237;": None,
         u"&#238;": None, u"&#239;": None, u"&#240;": None, u"&#241;": None, u"&#242;": None, u"&#243;": None,
         u"&#244;": None, u"&#245;": None, u"&#246;": None, u"&#247;": None, u"&#248;": None, u"&#249;": None,
         u"&#250;": None, u"&#251;": None, u"&#252;": None, u"&#253;": None, u"&#254;": None, u"&#255;": None,
         u"&#338;": None, u"&#339;": None, u"&#352;": None, u"&#353;": None, u"&#376;": None, u"&#402;": None,
         u"&#8211;": None, u"&#8212;": None, u"&#8216;": None, u"&#8217;": None, u"&#8218;": None,
         u"&#8220;": None, u"&#8221;": None, u"&#8222;": None, u"&#8224;": None, u"&#8225;": None,
         u"&#8226;": None, u"&#8230;": None, u"&#8240;": None, u"&#8364;": None, u"&#8482;": None}

ENTITY = {u"&nbsp;": None, u"&iexcl;": None, u"&cent;": None, u"&pound;": None, u"&curren;": None, u"&yen;": None,
          u"&brvbar;": None, u"&sect;": None, u"&uml;": None, u"&copy;": None, u"&ordf;": None, u"&laquo;": None,
          u"&not;": None, u"&shy;": None, u"&reg;": None, u"&macr;": None, u"&deg;": None, u"&plusmn;": None,
          u"&sup2;": None, u"&sup3;": None, u"&acute;": None, u"&micro;": None, u"&para;": None, u"&middot;": None,
          u"&cedil;": None, u"&sup1;": None, u"&ordm;": None, u"&raquo;": None, u"&frac14;": None, u"&frac12;": None,
          u"&frac34;": None, u"&iquest;": None, u"&Agrave;": None, u"&Aacute;": None, u"&Acirc;": None,
          u"&Atilde;": None, u"&Auml;": None, u"&Aring;": None, u"&AElig;": None, u"&Ccedil;": None,
          u"&Egrave;": None, u"&Eacute;": None, u"&Ecirc;": None, u"&Euml;": None, u"&Igrave;": None, u"&Iacute;": None,
          u"&Icirc;": None, u"&Iuml;": None, u"&ETH;": None, u"&Ntilde;": None, u"&Ograve;": None, u"&Oacute;": None,
          u"&Ocirc;": None, u"&Otilde;": None, u"&Ouml;": None, u"&times;": None, u"&Oslash;": None, u"&Ugrave;": None,
          u"&Uacute;": None, u"&Ucirc;": None, u"&Uuml;": None, u"&Yacute;": None, u"&THORN;": None, u"&szlig;": None,
          u"&agrave;": None, u"&aacute;": None, u"&acirc;": None, u"&atilde;": None, u"&auml;": None, u"&aring;": None,
          u"&aelig;": None, u"&ccedil;": None, u"&egrave;": None, u"&eacute;": None, u"&ecirc;": None, u"&euml;": None,
          u"&igrave;": None, u"&iacute;": None, u"&icirc;": None, u"&iuml;": None, u"&eth;": None, u"&ntilde;": None,
          u"&ograve;": None, u"&oacute;": None, u"&ocirc;": None, u"&otilde;": None, u"&ouml;": None, u"&divide;": None,
          u"&oslash;": None, u"&ugrave;": None, u"&uacute;": None, u"&ucirc;": None, u"&uuml;": None, u"&yacute;": None,
          u"&thorn;": None, u"&yuml;": None, u"&euro;": None}


HTML_ENTITIES = {u"&#32;": None, u"&#33;": None, u"&#34;": None, u"&#35;": None, u"&#36;": None, u"&#37;": None,
                 u"&#38;": None, u"&#39;": None, u"&#40;": None, u"&#41;": None, u"&#42;": None, u"&#43;": None,
                 u"&#44;": None, u"&#45;": None, u"&#46;": None, u"&#47;": None, u"&quot;": None, u"&amp;": None,
                 u"&#48;": None, u"&#49;": None, u"&#50;": None, u"&#51;": None, u"&#52;": None, u"&#53;": None,
                 u"&#54;": None, u"&#55;": None, u"&#56;": None, u"&#57;": None, u"&#58;": None, u"&#59;": None,
                 u"&#60;": None, u"&#61;": None, u"&#62;": None, u"&#63;": None, u"&lt;": None, u"&gt;": None,
                 u"&#64;": None, u"&#65;": None, u"&#66;": None, u"&#67;": None, u"&#68;": None, u"&#69;": None,
                 u"&#70;": None, u"&#71;": None, u"&#72;": None, u"&#73;": None, u"&#74;": None, u"&#75;": None,
                 u"&#76;": None, u"&#77;": None, u"&#78;": None, u"&#79;": None, u"&#80;": None, u"&#81;": None,
                 u"&#82;": None, u"&#83;": None, u"&#84;": None, u"&#85;": None, u"&#86;": None, u"&#87;": None,
                 u"&#88;": None, u"&#89;": None, u"&#90;": None, u"&#91;": None, u"&#92;": None, u"&#93;": None,
                 u"&#94;": None, u"&#95;": None, u"&#96;": None, u"&#97;": None, u"&#98;": None, u"&#99;": None,
                 u"&#100;": None, u"&#101;": None, u"&#102;": None, u"&#103;": None, u"&#104;": None, u"&#105;": None,
                 u"&#106;": None, u"&#107;": None, u"&#108;": None, u"&#109;": None, u"&#110;": None, u"&#111;": None,
                 u"&#112;": None, u"&#113;": None, u"&#114;": None, u"&#115;": None, u"&#116;": None, u"&#117;": None,
                 u"&#118;": None, u"&#119;": None, u"&#120;": None, u"&#121;": None, u"&#122;": None, u"&#123;": None,
                 u"&#124;": None, u"&#125;": None, u"&#126;": None, u"&#160;": None, u"&#161;": None, u"&#162;": None,
                 u"&#163;": None, u"&#164;": None, u"&#165;": None, u"&#166;": None, u"&#167;": None, u"&#168;": None,
                 u"&#169;": None, u"&#170;": None, u"&#171;": None, u"&#172;": None, u"&#173;": None, u"&#174;": None,
                 u"&#175;": None, u"&nbsp;": None, u"&iexcl;": None, u"&cent;": None, u"&pound;": None,
                 u"&curren;": None, u"&yen;": None, u"&brvbar;": None, u"&sect;": None, u"&uml;": None,
                 u"&copy;": None, u"&ordf;": None, u"&laquo;": None, u"&not;": None, u"&shy;": None, u"&reg;": None,
                 u"&macr;": None, u"&#176;": None, u"&#177;": None, u"&#178;": None, u"&#179;": None, u"&#180;": None,
                 u"&#181;": None, u"&#182;": None, u"&#183;": None, u"&#184;": None, u"&#185;": None, u"&#186;": None,
                 u"&#187;": None, u"&#188;": None, u"&#189;": None, u"&#190;": None, u"&#191;": None, u"&deg;": None,
                 u"&plusmn;": None, u"&sup2;": None, u"&sup3;": None, u"&micro;": None, u"&para;": None,
                 u"&middot;": None, u"&sup1;": None, u"&ordm;": None, u"&raquo;": None, u"&frac14;": None,
                 u"&frac12;": None, u"&frac34;": None, u"&iquest;": None, u"&#192;": None, u"&#193;": None,
                 u"&#194;": None, u"&#195;": None, u"&#196;": None, u"&#197;": None, u"&#198;": None, u"&#199;": None,
                 u"&#200;": None, u"&#201;": None, u"&#202;": None, u"&#203;": None, u"&#204;": None, u"&#205;": None,
                 u"&#206;": None, u"&#207;": None, u"&Atilde;": None, u"&Auml;": None, u"&Aring;": None,
                 u"&AElig;": None, u"&Euml;": None, u"&Iuml;": None, u"&#208;": None, u"&#209;": None, u"&#210;": None,
                 u"&#211;": None, u"&#212;": None, u"&#213;": None, u"&#214;": None, u"&#215;": None, u"&#216;": None,
                 u"&#217;": None, u"&#218;": None, u"&#219;": None, u"&#220;": None, u"&#221;": None, u"&#222;": None,
                 u"&#223;": None, u"&ETH;": None, u"&Ntilde;": None, u"&Otilde;": None, u"&Ouml;": None,
                 u"&times;": None, u"&Oslash;": None, u"&Uuml;": None, u"&THORN;": None, u"&szlig;": None,
                 u"&#224;": None, u"&#225;": None, u"&#226;": None, u"&#227;": None, u"&#228;": None, u"&#229;": None,
                 u"&#230;": None, u"&#231;": None, u"&#232;": None, u"&#233;": None, u"&#234;": None, u"&#235;": None,
                 u"&#236;": None, u"&#237;": None, u"&#238;": None, u"&#239;": None, u"&auml;": None, u"&aring;": None,
                 u"&aelig;": None, u"&euml;": None, u"&iuml;": None, u"&#240;": None, u"&#241;": None, u"&#242;": None,
                 u"&#243;": None, u"&#244;": None, u"&#245;": None, u"&#246;": None, u"&#247;": None, u"&#248;": None,
                 u"&#249;": None, u"&#250;": None, u"&#251;": None, u"&#252;": None, u"&#253;": None, u"&#254;": None,
                 u"&#255;": None, u"&eth;": None, u"&ntilde;": None, u"&otilde;": None, u"&ouml;": None,
                 u"&divide;": None, u"&oslash;": None, u"&uuml;": None, u"&thorn;": None, u"&yuml;": None,
                 u"&#338;": None, u"&#339;": None, u"&#352;": None, u"&#353;": None, u"&#376;": None, u"&#402;": None,
                 u"&#8211;": None, u"&#8212;": None, u"&#8216;": None, u"&#8217;": None, u"&#8218;": None,
                 u"&#8220;": None, u"&#8221;": None, u"&#8222;": None, u"&#8224;": None, u"&#8225;": None,
                 u"&#8226;": None, u"&#8230;": None, u"&#8240;": None, u"&#8364;": None, u"&#8482;": None,
                 u"&euro;": None}
