# coding: utf-8
PORQUES = {u"graças a": None, u"por causa de": None, u"por causa que": None, u"a causa de": None, u"a causa da": None,
           u"a causa do": None, u"a causa que": None, u"em atenção a": None, u"por efeito de": None,
           u"uma vez que": None, u"à conta de": None, u"por isso que": None, u"por motivo de": None,
           u"isso porque": None, u"em face de": None, u"por mérito de": None, u"por força de": None,
           u"na medida em que": None, u"por conta de": None, u"em resultado de": None, u"pois que": None,
           u"em razão de": None, u"sendo que": None, u"porque": None, u"porquanto": None, u"devido a": None,
           u"devido ao": None, u"por que": None, u"dado que": None, u"porquê": None, u"conquanto": None,
           u"por ação de": None, u"pelo poder de": None, u"por esse motivo": None, u"posto que": None,
           u"em virtude de": None, u"por obra de": None, u"à custa de": None, u"em função de": None, u"posto": None,
           u"já que": None, u"visto que": None, u"em consequência de": None, u"hipótese de": None, u"desse modo": None,
           u"por isto": None, u"logo,": None, u"como resultado": None, u"de modo consequente": None,
           u"em consequência": None, u"assim sendo": None, u"por conseguinte": None, u"consequentemente": None,
           u"à vista disso": None, u"em vista disso": None, u"isto posto": None, u"por consequência": None,
           u"por isso": None, u"portanto": None, u"logo": None, u"então": None, u"pois": None,
           u"diante do": None,
           u"diante de": None,
           u"diante da": None,
           u"xxxxxxxxxx": None,
           }
